title: "Baptiste MEssant"
description: "Portfolio â€“ CV & projets"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "aqua" # ou "mint", "sunrise", "plum", "neon", "dark", etc.

plugins:
  - jekyll-include-cache


